In [3]:
# Importing Modules
import pandas as pd
import numpy as np

In [4]:
# Referencing the China Averages File that has China to US Gold Currency Conversions
china_avgs = ('Resources/CNY2US.csv')

# Reading the data then displaying the top 5 results
df = pd.read_csv(china_avgs)
df.head()

         Date      Open      High       Low     Close  Adj Close  Volume
0  2013-01-01  0.160498  0.160764  0.160313  0.160498   0.160498     0.0
1  2013-01-02  0.160318  0.160764  0.160318  0.160318   0.160318     0.0
2  2013-01-03  0.160431  0.160764  0.160351  0.160431   0.160431     0.0
3  2013-01-04  0.160449  0.160764  0.160390  0.160449   0.160449     0.0
4  2013-01-07  0.160501  0.160785  0.160413  0.160501   0.160501     0.0

In [5]:
# Organizing the China Averages Files and creating a new DataFrame that groups by year and outputting the new results into a new DataFrame
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
columns_to_average = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]
average_annual_data = pd.DataFrame()

In [6]:
# Looping through columns in new DataFrame "average_annual_data" and then grouping by year and averaging each column
for column in columns_to_average:
    average_annual_data[column + '_Avg'] = df.groupby('Year')[column].mean()
    print(average_annual_data)

      Open_Avg
Year
2013  0.162788
2014  0.162589
2015  0.159428
2016  0.150712
2017  0.148015
2018  0.151464
2019  0.144865
2020  0.144999
2021  0.155041
2022  0.148908
      Open_Avg  High_Avg
Year
2013  0.162788  0.162975
2014  0.162589  0.163804
2015  0.159428  0.159507
2016  0.150712  0.150956
2017  0.148015  0.148368
2018  0.151464  0.151802
2019  0.144865  0.145136
2020  0.144999  0.145334
2021  0.155041  0.155340
2022  0.148908  0.149236
      Open_Avg  High_Avg   Low_Avg
Year
2013  0.162788  0.162975  0.162470
2014  0.162589  0.163804  0.162264
2015  0.159428  0.159507  0.159312
2016  0.150712  0.150956  0.150482
2017  0.148015  0.148368  0.147759
2018  0.151464  0.151802  0.151117
2019  0.144865  0.145136  0.144635
2020  0.144999  0.145334  0.144774
2021  0.155041  0.155340  0.154872
2022  0.148908  0.149236  0.148571
      Open_Avg  High_Avg   Low_Avg  Close_Avg
Year
2013  0.162788  0.162975  0.162470   0.162794
2014  0.162589  0.163804  0.162264   0.162588
2015  0.159428  0.159507  0.159312   0.159428
2016  0.150712  0.150956  0.150482   0.150762
2017  0.148015  0.148368  0.147759   0.148009
2018  0.151464  0.151802  0.151117   0.151426
2019  0.144865  0.145136  0.144635   0.144826
2020  0.144999  0.145334  0.144774   0.145000
2021  0.155041  0.155340  0.154872   0.155040
2022  0.148908  0.149236  0.148571   0.148907
      Open_Avg  High_Avg   Low_Avg  Close_Avg  Adj Close_Avg
Year
2013  0.162788  0.162975  0.162470   0.162794       0.162794
2014  0.162589  0.163804  0.162264   0.162588       0.162588
2015  0.159428  0.159507  0.159312   0.159428       0.159428
2016  0.150712  0.150956  0.150482   0.150762       0.150762
2017  0.148015  0.148368  0.147759   0.148009       0.148009
2018  0.151464  0.151802  0.151117   0.151426       0.151426
2019  0.144865  0.145136  0.144635   0.144826       0.144826
2020  0.144999  0.145334  0.144774   0.145000       0.145000
2021  0.155041  0.155340  0.154872   0.155040       0.155040
2022  0.148908  0.149236  0.148571   0.148907       0.148907
      Open_Avg  High_Avg   Low_Avg  Close_Avg  Adj Close_Avg  Volume_Avg
Year
2013  0.162788  0.162975  0.162470   0.162794       0.162794         0.0
2014  0.162589  0.163804  0.162264   0.162588       0.162588         0.0
2015  0.159428  0.159507  0.159312   0.159428       0.159428         0.0
2016  0.150712  0.150956  0.150482   0.150762       0.150762         0.0
2017  0.148015  0.148368  0.147759   0.148009       0.148009         0.0
2018  0.151464  0.151802  0.151117   0.151426       0.151426         0.0
2019  0.144865  0.145136  0.144635   0.144826       0.144826         0.0
2020  0.144999  0.145334  0.144774   0.145000       0.145000         0.0
2021  0.155041  0.155340  0.154872   0.155040       0.155040         0.0
2022  0.148908  0.149236  0.148571   0.148907       0.148907         0.0

In [6]:
# File export into => China_Averages.csv
average_annual_data.to_csv('Resources/CHINA_averages.csv', header=True)