In [1]:
#Importing dependencies
import pandas as pd
import numpy as np

In [3]:
#Reading csv
euros_avgs = ('Resources/EURO2US.csv')
df = pd.read_csv(euros_avgs)
df.head()

         Date      Open      High       Low     Close  Adj Close  Volume
0  2013-01-01  1.320132  1.322401  1.319592  1.320132   1.320132     0.0
1  2013-01-02  1.319784  1.329805  1.319435  1.319784   1.319784     0.0
2  2013-01-03  1.318392  1.318913  1.308900  1.318218   1.318218     0.0
3  2013-01-04  1.303101  1.306380  1.300052  1.303271   1.303271     0.0
4  2013-01-07  1.306848  1.309929  1.302060  1.306745   1.306745     0.0

In [4]:
#Pulling the years from the date time
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
columns_to_average = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]
average_annual_data = pd.DataFrame()

In [5]:
#Creating a loop to pull averages per year
for column in columns_to_average:
    average_annual_data[column + '_Avg'] = df.groupby('Year')[column].mean()
    print(average_annual_data)

      Open_Avg
Year
2013  1.328100
2014  1.329088
2015  1.110392
2016  1.107090
2017  1.129315
2018  1.181316
2019  1.119809
2020  1.141790
2021  1.183170
2022  1.053652
      Open_Avg  High_Avg
Year
2013  1.328100  1.332223
2014  1.329088  1.332128
2015  1.110392  1.115682
2016  1.107090  1.111083
2017  1.129315  1.132780
2018  1.181316  1.184981
2019  1.119809  1.122107
2020  1.141790  1.145647
2021  1.183170  1.185783
2022  1.053652  1.058114
      Open_Avg  High_Avg   Low_Avg
Year
2013  1.328100  1.332223  1.323996
2014  1.329088  1.332128  1.325668
2015  1.110392  1.115682  1.105141
2016  1.107090  1.111083  1.103185
2017  1.129315  1.132780  1.126167
2018  1.181316  1.184981  1.177585
2019  1.119809  1.122107  1.117334
2020  1.141790  1.145647  1.138118
2021  1.183170  1.185783  1.180146
2022  1.053652  1.058114  1.049076
      Open_Avg  High_Avg   Low_Avg  Close_Avg
Year
2013  1.328100  1.332223  1.323996   1.328112
2014  1.329088  1.332128  1.325668   1.329099
2015  1.110392  1.115682  1.105141   1.110387
2016  1.107090  1.111083  1.103185   1.107110
2017  1.129315  1.132780  1.126167   1.129330
2018  1.181316  1.184981  1.177585   1.181330
2019  1.119809  1.122107  1.117334   1.119835
2020  1.141790  1.145647  1.138118   1.141856
2021  1.183170  1.185783  1.180146   1.183219
2022  1.053652  1.058114  1.049076   1.053654
      Open_Avg  High_Avg   Low_Avg  Close_Avg  Adj Close_Avg
Year
2013  1.328100  1.332223  1.323996   1.328112       1.328112
2014  1.329088  1.332128  1.325668   1.329099       1.329099
2015  1.110392  1.115682  1.105141   1.110387       1.110387
2016  1.107090  1.111083  1.103185   1.107110       1.107110
2017  1.129315  1.132780  1.126167   1.129330       1.129330
2018  1.181316  1.184981  1.177585   1.181330       1.181330
2019  1.119809  1.122107  1.117334   1.119835       1.119835
2020  1.141790  1.145647  1.138118   1.141856       1.141856
2021  1.183170  1.185783  1.180146   1.183219       1.183219
2022  1.053652  1.058114  1.049076   1.053654       1.053654
      Open_Avg  High_Avg   Low_Avg  Close_Avg  Adj Close_Avg  Volume_Avg
Year
2013  1.328100  1.332223  1.323996   1.328112       1.328112         0.0
2014  1.329088  1.332128  1.325668   1.329099       1.329099         0.0
2015  1.110392  1.115682  1.105141   1.110387       1.110387         0.0
2016  1.107090  1.111083  1.103185   1.107110       1.107110         0.0
2017  1.129315  1.132780  1.126167   1.129330       1.129330         0.0
2018  1.181316  1.184981  1.177585   1.181330       1.181330         0.0
2019  1.119809  1.122107  1.117334   1.119835       1.119835         0.0
2020  1.141790  1.145647  1.138118   1.141856       1.141856         0.0
2021  1.183170  1.185783  1.180146   1.183219       1.183219         0.0
2022  1.053652  1.058114  1.049076   1.053654       1.053654         0.0

In [6]:
#Exporting new csv file
average_annual_data.to_csv('Resources/EUROS_averages.csv', header=True)