In [1]:
import pandas as pd
import numpy as np

In [2]:
russia_avgs = ('..\Resources/RUBLE2US.csv')
df = pd.read_csv(russia_avgs)
df.head()

         Date      Open      High       Low     Close  Adj Close  Volume
0  2013-01-01  0.032785  0.032785  0.032646  0.032785   0.032785     0.0
1  2013-01-02  0.032942  0.033231  0.032689  0.032963   0.032963     0.0
2  2013-01-03  0.033160  0.033232  0.032934  0.033160   0.033160     0.0
3  2013-01-04  0.033025  0.033100  0.032711  0.033035   0.033035     0.0
4  2013-01-07  0.033019  0.033105  0.032806  0.033019   0.033019     0.0

In [3]:
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
columns_to_average = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]
average_annual_data = pd.DataFrame()

In [4]:
for column in columns_to_average:
    average_annual_data[column + '_Avg'] = df.groupby('Year')[column].mean()
    print(average_annual_data)

      Open_Avg
Year
2013  0.031463
2014  0.026568
2015  0.016556
2016  0.015004
2017  0.017161
2018  0.016015
2019  0.015465
2020  0.013913
2021  0.013576
2022  0.014868
      Open_Avg  High_Avg
Year
2013  0.031463  0.031559
2014  0.026568  0.026714
2015  0.016556  0.016721
2016  0.015004  0.015109
2017  0.017161  0.017262
2018  0.016015  0.016111
2019  0.015465  0.015520
2020  0.013913  0.014002
2021  0.013576  0.013637
2022  0.014868  0.015195
      Open_Avg  High_Avg   Low_Avg
Year
2013  0.031463  0.031559  0.031337
2014  0.026568  0.026714  0.026345
2015  0.016556  0.016721  0.016339
2016  0.015004  0.015109  0.014910
2017  0.017161  0.017262  0.017084
2018  0.016015  0.016111  0.015924
2019  0.015465  0.015520  0.015412
2020  0.013913  0.014002  0.013813
2021  0.013576  0.013637  0.013518
2022  0.014868  0.015195  0.014605
      Open_Avg  High_Avg   Low_Avg  Close_Avg
Year
2013  0.031463  0.031559  0.031337   0.031465
2014  0.026568  0.026714  0.026345   0.026569
2015  0.016556  0.016721  0.016339   0.016527
2016  0.015004  0.015109  0.014910   0.020301
2017  0.017161  0.017262  0.017084   0.017161
2018  0.016015  0.016111  0.015924   0.016014
2019  0.015465  0.015520  0.015412   0.015465
2020  0.013913  0.014002  0.013813   0.013913
2021  0.013576  0.013637  0.013518   0.013576
2022  0.014868  0.015195  0.014605   0.014798
      Open_Avg  High_Avg   Low_Avg  Close_Avg  Adj Close_Avg
Year
2013  0.031463  0.031559  0.031337   0.031465       0.031465
2014  0.026568  0.026714  0.026345   0.026569       0.026569
2015  0.016556  0.016721  0.016339   0.016527       0.016527
2016  0.015004  0.015109  0.014910   0.020301       0.020301
2017  0.017161  0.017262  0.017084   0.017161       0.017161
2018  0.016015  0.016111  0.015924   0.016014       0.016014
2019  0.015465  0.015520  0.015412   0.015465       0.015465
2020  0.013913  0.014002  0.013813   0.013913       0.013913
2021  0.013576  0.013637  0.013518   0.013576       0.013576
2022  0.014868  0.015195  0.014605   0.014798       0.014798
      Open_Avg  High_Avg   Low_Avg  Close_Avg  Adj Close_Avg  Volume_Avg
Year
2013  0.031463  0.031559  0.031337   0.031465       0.031465         0.0
2014  0.026568  0.026714  0.026345   0.026569       0.026569         0.0
2015  0.016556  0.016721  0.016339   0.016527       0.016527         0.0
2016  0.015004  0.015109  0.014910   0.020301       0.020301         0.0
2017  0.017161  0.017262  0.017084   0.017161       0.017161         0.0
2018  0.016015  0.016111  0.015924   0.016014       0.016014         0.0
2019  0.015465  0.015520  0.015412   0.015465       0.015465         0.0
2020  0.013913  0.014002  0.013813   0.013913       0.013913         0.0
2021  0.013576  0.013637  0.013518   0.013576       0.013576         0.0
2022  0.014868  0.015195  0.014605   0.014798       0.014798         0.0

In [5]:
average_annual_data.to_csv('..\Resources/RUSSIA_Conversion_averages.csv', header=True)